### ISSUE TITLE
linking issue: missing .lib files

### ISSUE THREAD

**Issue by biemster** [ThuanLeUte/ble-beacons-st17h66_fw#1]
When trying to compile the IBEACON firmware, the compiler complains it can't find a .lib file:
```
.\Objects\IBEACON.axf: error: L6002U: Could not open file ..\lib\rf.lib: No such file or directory
Finished: 0 information, 0 warning, 0 error and 1 fatal error messages.
```
Upon inspection, this is indeed not present in the `lib` directory. The project file includes three files from this directory: `rf.lib`, `ble_host.lib` and `cksys.lib`. The SDK available in `https://github.com/17HXX/BLE5_ST17H66` has two of these lib files, but `cksys.lib` I'm not able to find anywhere.

**Comment by ThuanLeUte** [comment]
Thank you for your comment. I will updated and send you the information.

What is your application ?

**Comment by biemster** [comment]
Thanks @ThuanLeUte ! I'm working on a firmware for https://github.com/seemoo-lab/openhaystack, and after that I'm going to use them for wireless buttons for home automation.

**Comment by biemster** [comment]
Actually I just saw that you have several repositories for the ST17H66, and this onoe seems to be the oldest. I'll have a look at the other ones first, if they compile fine you can close this ticket.

**Comment by biemster** [comment]
Your repo https://github.com/ThuanLeUte/ble-st17h66_fw_power_consumption has a similar issue except it is not using `cksys.lib`, and it compiles if I change the path to the two remaining libs to the ones in https://github.com/17HXX/BLE5_ST17H66/tree/master/ST17H66_SDK_3.0.9/lib so I will move my development to that repo. I also found newer SDKs here: https://github.com/Qi-Yang0914?tab=repositories
